# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: demoworkspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: <enter-your-resource-group-name>
  ado_service_connection_aml_ws: <enter-your-aml-workspace-name>