# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: demoworkspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  resource_group: mlsops-june2023
  aml_workspace: mlsops-june2023
